In [9]:
#Program to create a Series by passing a list of values, letting pandas create a default integer index.

import pandas as pd
import numpy as np
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [13]:
#Program to create a DataFrame by passing a NumPy array, with a datetime index and labeled columns.

import pandas as pd
dates = pd.date_range("20130101", periods=6)
dates

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.237707 -0.889426 -1.298120  0.196717
2013-01-02  0.578622 -0.106448 -2.006477  1.440606
2013-01-03 -1.277443  2.373558 -0.817580  0.715114
2013-01-04 -1.769441  1.199784  0.324390 -1.192152
2013-01-05  0.046751  0.713011  1.528201  0.875964
2013-01-06 -0.860665  0.196670 -0.158032 -1.292257

In [16]:
#Program to create DataFrame by passing a dictionary of objects that can be converted into a series-like structure.
import pandas as pd
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)


df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [18]:
# Program to Concatenating pandas objects together with concat()
import  pandas as pd
df = pd.DataFrame(np.random.randn(10, 4))

df

# break it into pieces
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

          0         1         2         3
0  1.957248 -0.048037  0.517775  0.488630
1 -2.902540  0.392608  0.572879 -0.723406
2 -0.148182  0.696662  0.202327 -0.399262
3 -0.021877 -0.511842  1.227149 -0.145540
4  1.269299 -0.752170 -0.192800  1.038806
5 -0.262298 -1.618707 -3.519914  0.845342
6  0.892940  0.187268  0.667620 -0.907721
7  0.606885 -0.620487  1.542449  1.313969
8  0.957734  0.811360  0.193600 -0.384521
9 -0.530627  0.431747 -0.612605 -0.171273

In [26]:
#Program to set a  column automatically aligns the data by the index.
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64